### PR TITLE
use setDefinition and not setService to customize services

### PR DESCRIPTION
**Pull request by riccardonar**

### CODE REVIEW

**Comment by goetas** [comment]
can you please remove the `composer.lock` from this PR ?

**Comment by riccardonar** [comment]
> can you please remove the `composer.lock` from this PR ?

No problem, but without it install not works

**Comment by goetas** [comment]
Ah, right, it needs the latest version. Can you resolve the conflict then?

**Comment by goetas** [comment]
closing in favor of https://github.com/doctrine/DoctrineMigrationsBundle/pull/323

**Pull request closed without merging**
