### PR TITLE
var directory for symfony >= 2.8

### PR DESCRIPTION
**Pull request by JuanLuisGarciaBorrego**
Hello, I propose to create a new branch for this bundle for versions of symfony 2.8 or higher.

I propose to create migration files in the var / directory instead of app / (currently in this bundle).
So we can give permissions to the var / folder.
regards

### CODE REVIEW

**Comment by xabbuh** [comment]
I would not recommend to make this change. The `var/`directory is not meant to keep application files (its files are ignored by Git by default when using the Symfony Standard Edition).

By the way, the new directory structure was introduced with Symfony 3.0 (not 2.8).

**Comment by mikeSimonson** [comment]
In this case I propose to close this PR.

Can you make a new PR that add the note in the documentation that the console is in the bin directory for symfony 3.0 ?

Thanks @xabbuh @JuanLuisGarciaBorrego

**Comment by JuanLuisGarciaBorrego** [comment]
Okay, I will complete the documentation to access the console symfony.

@xabbuh Symfony 2.8 has the same directory structure that symfony3.

**Comment by stof** [comment]
@JuanLuisGarciaBorrego no it does not. symfony-standard 2.8 provides the 2.x directory structure: https://github.com/symfony/symfony-standard/tree/2.8

**Comment by JuanLuisGarciaBorrego** [comment]
Thank you for your response @stof @xabbuh @mikeSimonson 
I see that in version 2.8 on github the new structure does not appear, but just installed version 2.8 and symfony if it appears.

#Composer.json 
`"symfony / symfony": "2.8. *"`

Symfony Instalador
`$ Symfony new projectSample 2.8`

**Comment by stof** [comment]
I just ran the installer asking for a new 2.8 project, and I got the old structure, not the new one. So something looks wrong in what you are reporting.

**Comment by JuanLuisGarciaBorrego** [comment]
.. i have the versión of symfony Installer 1.5.0.

The composer.json generated is this:

    "require": {
        "php": ">=5.3.9",
        "symfony/symfony": "2.8.*",
        "doctrine/orm": "^2.4.8",
        "doctrine/doctrine-bundle": "~1.4",
        "symfony/swiftmailer-bundle": "~2.3",
        "symfony/monolog-bundle": "~2.4",
        "sensio/distribution-bundle": "~5.0",
        "sensio/framework-extra-bundle": "^3.0.2",
        "incenteev/composer-parameter-handler": "~2.0"
    },

**Comment by stof** [comment]
The composer.json does not control the project structure

**Comment by JuanLuisGarciaBorrego** [comment]
Yes, I know that the structure is not seen in the composer.json but yes the installed version of symfony.
Any recommendation?
Thanks @stof

**Comment by JuanLuisGarciaBorrego** [comment]
I deleted and installed the installer again and now symfony creates the directories 2.x.
I 'm sorry =( 

thank you very much @stof

**Pull request closed without merging**
