### PR TITLE
Add new doctrine current command

### PR DESCRIPTION
**Pull request by goetas**
Integrates https://github.com/doctrine/migrations/pull/965 into the bundle

### CODE REVIEW

**Comment by greg0ire** [comment]
Shouldn't the `doctrine/migrations` requirement be bumped?

**Comment by goetas** [comment]
Currently we are requiting `doctrine/migrations:^3.0@dev`, until 3.0.0 is not released, no version bump is required

**Comment by goetas** [comment]
But only now i see the test failure... but i have no idea how to fix it...

**Comment by greg0ire** [comment]
Besides pinning to a given commit, I have no idea either

**Comment by greg0ire** [comment]
Ah wait I know, try to use `master`. Right now it's installing the alpha1 tag, which matches `@dev`

**Comment by goetas** [comment]
like this?

**Comment by greg0ire** [comment]
yeah I think that should work

**Comment by goetas** [comment]
yeah

**Pull request merged**
