### PR TITLE
replace asserting doctrine is instance of Registry with assert it is proper interface

### LINKED ISSUE #400: Warning: assert(): assert($doctrine instanceof Registry) failed when you have custom implementation of ManagerRegistry
after upgrade to version 2.2.2 i get an warning `Warning: assert(): assert($doctrine instanceof Registry)` because we use custom implementation of `Doctrine\Persistence\ManagerRegistry`

in `Doctrine\Bundle\MigrationsBundle\Command\Helper\DoctrineCommandHelper` you should not assert instanceof `Doctrine\Bundle\DoctrineBundle\Registry` but Doctrine\Persistence\ManagerRegistry instead as you only need method `getManagerNames` from this interface

### PR DESCRIPTION
**Pull request by slawro**
see #400

### CODE REVIEW

**Comment by greg0ire** [comment]
I'm having a look at the static analysis issue.

In the meantime, 
- please improve your commit message according to [the contributing guide](https://www.doctrine-project.org/contribute/index.html#working-on-topic-branches). In your case, it's more about the form than about the contents 👍
- please associate your email address with your Github account, or change the
email in your commits to an address already associated with it. If you do not
want to expose your personal email address, you may use
`$userName@users.noreply.github.com`, that way we can still reach you through Github.
Additionally, you will get credit for this contribution on your Github profile.

**Comment by greg0ire** [comment]
PR that fixes the SA issue: https://github.com/doctrine/DoctrineMigrationsBundle/pull/402

**Comment by slawro** [comment]
@greg0ire thank you very much for help and suggestions, it is very helpful from You

ive changed what you suggested, hope that all is correct now
let me know if you have any other suggestions

**Review by greg0ire — APPROVED** [review]

**Comment by greg0ire** [comment]
Thanks @slawro

**Pull request merged**
