### PR TITLE
Fix .gitattribute 

### PR DESCRIPTION
**Pull request by connorhu**
Mostly fixes because of #535
- updated Tests
- removed phpstan neon
- added phpstan baseline
- added docs

### CODE REVIEW

**Comment by connorhu** [comment]
A couple of weeks ago I was playing around with the problem of whether there is any way to check the export-ignore setting with "deny all".
I ended up with a GHA task, but I'm not completely satisfied with it yet (I'm not a git wizard).

In a file it was listed what was allowed in the root directory and in case of PR a job checked if the ones in the root were allowed.

**Comment by SenseException** [comment]
Thanks for the contribution. Could you please [squash](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History#_squashing) your commits?

**Comment by connorhu** [comment]
@SenseException Sure!

**Comment by greg0ire** [comment]
Thanks @connorhu !

**Pull request merged**
