### PR TITLE
make organize-migrations usable in XML configs

### LINKED ISSUE #175: Add support for "organize_migrations" configuration
When I use a migrations.yml to configure Doctrine Migrations, I have the possibility to set `organize_migrations: year_and_month` to have a directory per month and year. With this bundle this is not possible yet.

### PR DESCRIPTION
**Pull request by xabbuh**
This fixes #175.

### CODE REVIEW

**Comment by mikeSimonson** [comment]
@xabbuh Thanks. Can you modify the tests so that this path is tested too ?

**Comment by mikeSimonson** [comment]
@xabbuh Thanks

**Comment by xabbuh** [comment]
@mikeSimonson Sorry, I didn't find the time to update the tests. Are you doing that right now? Otherwise I can try to update them this weekend.

**Comment by mikeSimonson** [comment]
@xabbuh If you can find the time that would be nice.

**Pull request merged**
