### PR TITLE
Introduce EnvironmentAwareMigrationInterface

### PR DESCRIPTION
**Pull request by alexndlm**
In migrations, it's best to avoid using dynamic values or services that could cause unexpected issues. However, including the current environment can be really helpful. It lets us skip migrations for testing or production and set different default values depending on the environment.

### CODE REVIEW

**Comment by alexndlm** [comment]
@derrabus wdyt?

**Comment by greg0ire** [comment]
It seems there are CI jobs failing. Please take a look at [this guide](https://www.doctrine-project.org/contribute/#dealing-with-checks-and-tools) for more on how to handle those.

**Comment by alexndlm** [comment]
@greg0ire, thanks, fixed.

**Comment by greg0ire** [comment]
Blocked by #531

**Comment by greg0ire** [comment]
Retargeting to 3.4.x since this is no bugfix

**Comment by ERuban** [comment]
Any news on that?

**Comment by derrabus** [comment]
I'd like to close this PR. I don't think, adding more FooAwareMigrationInterfaces are the proper way forward. Instead, we should find a way to leverage DI for migrations as I layed out in https://github.com/doctrine/DoctrineMigrationsBundle/issues/521#issuecomment-1855593824.

**Pull request closed without merging**
